/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AnalyseMap: typeof import('./../components/map/component/Panels/analyseMap.vue')['default']
    AnimationMap: typeof import('./../components/map/component/Panels/animationMap.vue')['default']
    BigPanel: typeof import('./../components/map/component/bigPanel.vue')['default']
    Brp: typeof import('./../components/map/brp.vue')['default']
    Card: typeof import('./../components/map/card.vue')['default']
    CircleForm: typeof import('./../components/map/form/circleForm.vue')['default']
    Clear: typeof import('./../components/map/clear.vue')['default']
    Compass: typeof import('./../components/map/compass.vue')['default']
    D25Panel: typeof import('./../components/map/component/d25Panel.vue')['default']
    D3Panel: typeof import('./../components/map/component/d3Panel.vue')['default']
    DragPanel: typeof import('./../components/map/dragPanel/index.vue')['default']
    ElAutocomplete: typeof import('element-plus/es')['ElAutocomplete']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    FontLoader: typeof import('./../components/three/fontLoader.vue')['default']
    GridControl: typeof import('./../components/map/dragPanel/gridControl.vue')['default']
    Icon: typeof import('./../components/Icon/src/Icon.vue')['default']
    LineForm: typeof import('./../components/map/form/lineForm.vue')['default']
    Map: typeof import('./../components/map/index.vue')['default']
    Modals: typeof import('./../components/Modals/index.vue')['default']
    ModeChange: typeof import('./../components/common/ModeChange.vue')['default']
    PointForm: typeof import('./../components/map/form/pointForm.vue')['default']
    PolygonForm: typeof import('./../components/map/form/polygonForm.vue')['default']
    RoutePlan: typeof import('./../components/map/component/routePlan.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Setting: typeof import('./../components/Modals/setting.vue')['default']
    SwipeControl: typeof import('./../components/map/dragPanel/swipeControl.vue')['default']
    ThreejsViewerBuilding: typeof import('./../components/BIM/ThreejsViewerBuilding.vue')['default']
    ThreejsViewerRegion: typeof import('./../components/BIM/ThreejsViewerRegion.vue')['default']
    TopicLayerCard: typeof import('./../components/map/component/topicLayerCard.vue')['default']
    Trp: typeof import('./../components/map/trp.vue')['default']
    VectorLayerHight: typeof import('./../components/map/component/Panels/vectorLayerHight.vue')['default']
    WaterMarkerControl: typeof import('./../components/map/dragPanel/waterMarkerControl.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
